# Generated by Django 5.1.6 on 2025-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='hours',
        ),
        migrations.AddField(
            model_name='buildings',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
