# Generated by Django 5.1.6 on 2025-02-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_access', '0002_remove_buildings_hours_buildings_end_time_and_more'),
        ('login', '0006_rename_number_of_times_used_user_times_used'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buildings',
            new_name='Building',
        ),
    ]
