[project]
name = "lock-out-hero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-allauth>=65.4.1",
    "django>=5.1.6",
]
