# Generated by Django 5.1.6 on 2025-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
