# Generated by Django 5.1.6 on 2025-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_access', '0001_initial'),
        ('login', '0002_alter_user_gender_alter_user_j_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Number_of_times_used',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='accessible_buildings',
            field=models.ManyToManyField(related_name='Accessible_Buildings', to='building_access.buildings'),
        ),
        migrations.AddField(
            model_name='user',
            name='dorm',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
