# Generated by Django 5.1.6 on 2025-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_number_of_times_used_user_accessible_buildings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Number_of_times_used',
            field=models.IntegerField(default=0),
        ),
    ]
