# Generated by Django 5.1.6 on 2025-02-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_number_of_times_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Number_of_times_used',
            new_name='number_of_times_used',
        ),
    ]
